### ISSUE TITLE
Little circle intermittently snaps back to zero position on outward drag release

### ISSUE THREAD

**Issue by suchow** [Dallinger/identityfusion#10]
When dragging the small circle outward from the large circle in small steps, the small circle intermittently (~5% of the time) jumps back to the center of the large circle.

# Steps to reproduce
1. Drag the small circle to the center of the large circle.
2. Drag the small circle slightly to the left and then release. Then drag again. Continue for 10 drags, then go back to step 1.

# Evidence
http://www.giphy.com/gifs/3ohzdZSl65NHNWiFpu

In this video, I go through steps 1 & 2 a first time without observing the issue and so return to step 1 and reset. The next time through it jumps back without me having dragged it.

**Comment by davisagli** [comment]
I think this is fixed.

**Comment by suchow** [comment]
Yes, fixed!
