### ISSUE TITLE
Uncontrollable position

### ISSUE THREAD

**Issue by suchow** [Dallinger/identityfusion#11]
I'm seeing a weird issue where, when I drag the small circle right, it sometimes pops back to the center of the large circle. See the video below, which is a series of leftward drags and releases.

![sep-25-2017 16-56-41](https://user-images.githubusercontent.com/613981/30831566-df427afe-a215-11e7-8687-00ae52c0211e.gif)

**Comment by cguardia** [comment]
I was not able to replicate this using Chrome on Linux. What platform/browser are you using?

**Comment by cguardia** [comment]
It was on a Mac, using Chrome 61.0.3163.100.

**Comment by cguardia** [comment]
This problem was fixed on #10, but Dallinger was using an old version of identity fusion. Closing.
